const createMockModel = () => ({
  findUnique: jest.fn(),
  findFirst: jest.fn(),
  findMany: jest.fn(),
  create: jest.fn(),
  createMany: jest.fn(),
  update: jest.fn(),
  updateMany: jest.fn(),
  upsert: jest.fn(),
  delete: jest.fn(),
  deleteMany: jest.fn(),
  count: jest.fn(),
  aggregate: jest.fn(),
  groupBy: jest.fn(),
});

export const mockPrismaService = {
  school: createMockModel(),
  schoolGroup: createMockModel(),
  schoolLevel: createMockModel(),
  schoolFiliere: createMockModel(),
  user: createMockModel(),
  userSchool: createMockModel(),
  student: createMockModel(),
  class: createMockModel(),
  teacher: createMockModel(),
  subject: createMockModel(),
  teacherSubject: createMockModel(),
  schoolYear: createMockModel(),
  academicPeriod: createMockModel(),
  grade: createMockModel(),
  reportCard: createMockModel(),
  paymentPlan: createMockModel(),
  levelTuition: createMockModel(),
  payment: createMockModel(),
  paymentAuditLog: createMockModel(),
  timetable: createMockModel(),
  attendanceSession: createMockModel(),
  attendance: createMockModel(),
  incident: createMockModel(),
  syncOperation: createMockModel(),
  studentParent: createMockModel(),
  refreshToken: createMockModel(),
  passwordResetToken: createMockModel(),
  invitation: createMockModel(),
  classProgressionOption: createMockModel(),
  teacherProgressionVote: createMockModel(),
  studentProgression: createMockModel(),
  commune: createMockModel(),
  city: createMockModel(),
  $transaction: jest.fn((cb: any) => cb(mockPrismaService)),
  $connect: jest.fn(),
  $disconnect: jest.fn(),
};
